import type { Role } from "@prisma/client";

// Central role-based access control map. Every admin route/server action
// should check `can(role, permission)` rather than re-implementing role
// checks ad hoc — this is the single place the permission matrix lives.

export const PERMISSIONS = {
  VIEW_ADMIN_DASHBOARD: "VIEW_ADMIN_DASHBOARD",
  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
  MANAGE_CATEGORIES: "MANAGE_CATEGORIES",
  MANAGE_SUPPLIERS: "MANAGE_SUPPLIERS",
  MANAGE_STORES: "MANAGE_STORES",
  MANAGE_ORDERS: "MANAGE_ORDERS",
  MANAGE_SHOP_FOR_ME: "MANAGE_SHOP_FOR_ME",
  MANAGE_SOURCING: "MANAGE_SOURCING",
  MANAGE_WAREHOUSE: "MANAGE_WAREHOUSE",
  MANAGE_CONSOLIDATION: "MANAGE_CONSOLIDATION",
  MANAGE_SHIPMENTS: "MANAGE_SHIPMENTS",
  MANAGE_SHIPPING_RATES: "MANAGE_SHIPPING_RATES",
  MANAGE_PAYMENTS: "MANAGE_PAYMENTS",
  MANAGE_WALLETS: "MANAGE_WALLETS",
  MANAGE_REFUNDS: "MANAGE_REFUNDS",
  MANAGE_CUSTOMERS: "MANAGE_CUSTOMERS",
  MANAGE_SELLERS: "MANAGE_SELLERS",
  MANAGE_COUPONS: "MANAGE_COUPONS",
  MANAGE_REVIEWS: "MANAGE_REVIEWS",
  MANAGE_SUPPORT: "MANAGE_SUPPORT",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
  SELLER_DASHBOARD: "SELLER_DASHBOARD",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_ADMIN_PERMISSIONS = Object.values(PERMISSIONS).filter(
  (p) => p !== PERMISSIONS.SELLER_DASHBOARD,
) as Permission[];

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL_ADMIN_PERMISSIONS,
  OPERATIONS_ADMIN: ALL_ADMIN_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.MANAGE_SETTINGS && p !== PERMISSIONS.MANAGE_USERS,
  ),
  SOURCING_STAFF: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_SOURCING,
    PERMISSIONS.MANAGE_SHOP_FOR_ME,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.MANAGE_STORES,
  ],
  WAREHOUSE_STAFF: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_WAREHOUSE,
    PERMISSIONS.MANAGE_CONSOLIDATION,
  ],
  SHIPPING_STAFF: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_SHIPMENTS,
    PERMISSIONS.MANAGE_SHIPPING_RATES,
  ],
  FINANCE_STAFF: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_WALLETS,
    PERMISSIONS.MANAGE_REFUNDS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  CUSTOMER_SUPPORT: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.MANAGE_CUSTOMERS,
  ],
  SELLER: [PERMISSIONS.SELLER_DASHBOARD],
  CUSTOMER: [],
};

export function can(role: Role | undefined | null, permission: Permission): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function isStaffRole(role: Role | undefined | null): boolean {
  if (!role) return false;
  return role !== "CUSTOMER" && role !== "SELLER";
}

export const ADMIN_ROLES: Role[] = [
  "SUPER_ADMIN",
  "OPERATIONS_ADMIN",
  "SOURCING_STAFF",
  "WAREHOUSE_STAFF",
  "SHIPPING_STAFF",
  "FINANCE_STAFF",
  "CUSTOMER_SUPPORT",
];

export const ROLE_LABELS: Record<Role, string> = {
  SUPER_ADMIN: "Super Admin",
  OPERATIONS_ADMIN: "Operations Admin",
  SOURCING_STAFF: "Sourcing Staff",
  WAREHOUSE_STAFF: "Warehouse Staff",
  SHIPPING_STAFF: "Shipping Staff",
  FINANCE_STAFF: "Finance Staff",
  CUSTOMER_SUPPORT: "Customer Support",
  SELLER: "Seller",
  CUSTOMER: "Customer",
};
