import { LegalPage } from "@/components/legal/LegalPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How ATG Mall collects, uses and protects your personal information.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      lastUpdated="September 2026"
      intro="This Privacy Policy explains what personal information ATG Mall (operated by Apex Terra Global Limited) collects, how we use it, and the choices you have."
    >
      <h2>1. Information we collect</h2>
      <p>We collect information you provide directly, and information generated by your use of ATG Mall:</p>
      <ul>
        <li><strong>Account information:</strong> full name, email address, phone number, password (stored as a salted hash, never in plain text), and preferred country.</li>
        <li><strong>Order &amp; sourcing information:</strong> delivery addresses, product links/descriptions you submit, order and quotation history.</li>
        <li><strong>Payment information:</strong> we do not store full card numbers on our servers; payments are processed by payment providers, and wallet transactions are recorded as a ledger tied to your account.</li>
        <li><strong>Package &amp; shipment information:</strong> warehouse receipts, weights/dimensions, tracking events, and delivery status.</li>
        <li><strong>Support information:</strong> messages you send through support tickets, chat or email.</li>
        <li><strong>Usage information:</strong> pages visited and actions taken on the platform, used to operate and improve the service.</li>
      </ul>

      <h2>2. How we use your information</h2>
      <ul>
        <li>To create and manage your account, and authenticate you when you sign in.</li>
        <li>To process orders, sourcing requests, payments, wallet transactions, packages and shipments.</li>
        <li>To communicate with you about your orders, packages, shipments and support requests, via email, SMS, WhatsApp or in-app notifications, depending on the channel and your preferences.</li>
        <li>To detect and prevent fraud, abuse and prohibited-item shipments.</li>
        <li>To comply with legal and customs obligations relevant to cross-border shipping.</li>
      </ul>

      <h2>3. Who we share information with</h2>
      <p>We share information only where necessary to provide the service, including with:</p>
      <ul>
        <li>Suppliers, to fulfil purchases made on your behalf (typically limited to what a purchase requires — product, quantity, and shipping destination).</li>
        <li>Shipping, freight and customs partners, to move and clear your packages.</li>
        <li>Payment processors, to process payments and deposits.</li>
        <li>Staff within Apex Terra Global Limited who need access to serve your account (for example, warehouse, sourcing, or support staff), governed by role-based access controls.</li>
      </ul>
      <p>We do not sell your personal information.</p>

      <h2>4. Data retention</h2>
      <p>
        We retain account, order and transaction records for as long as your account is active and for a reasonable
        period afterward, as needed for accounting, dispute resolution, and legal or tax obligations.
      </p>

      <h2>5. Data security</h2>
      <p>
        We apply reasonable technical and organizational safeguards, including password hashing, role-based access
        control for staff, and access logging for sensitive actions. No system is completely secure, and we cannot
        guarantee absolute security of information transmitted over the internet.
      </p>

      <h2>6. Your choices</h2>
      <ul>
        <li>You can review and update your profile and address information from your account at any time.</li>
        <li>You can contact us to request a copy of, correction to, or deletion of your personal information, subject to our legal and operational retention needs (for example, records tied to a completed order).</li>
        <li>You can manage notification preferences where offered in your account settings.</li>
      </ul>

      <h2>7. International data handling</h2>
      <p>
        Because ATG Mall coordinates purchases from Chinese suppliers and international shipping, limited order and
        shipping information (such as product, quantity and delivery destination) is necessarily shared with
        suppliers and logistics partners outside your country of residence in order to fulfil your order.
      </p>

      <h2>8. Children</h2>
      <p>ATG Mall is intended for use by adults capable of entering a binding contract. We do not knowingly collect information from children.</p>

      <h2>9. Changes to this policy</h2>
      <p>We may update this Privacy Policy from time to time. Material changes will be reflected by an updated "Last updated" date above.</p>

      <h2>10. Contact us</h2>
      <p>
        For privacy questions or requests, contact us at{" "}
        <a href="mailto:support@apexterraglobal.com">support@apexterraglobal.com</a>.
      </p>
    </LegalPage>
  );
}
